openapi: 3.0.3
info:
  title: API сервер для проекта «Шесть городов».
  description: |-
    * Список ресурсов и маршрутов сервера «Шесть городов».
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
tags:
  - name: users
    description: Действия с пользователем.
  - name: offers
    description: Действия с объявлениями.
  - name: categories
    description: Действия с категориями.

paths:
  /users/register:
    post:
      tags:
        - users
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя.

  /users/login:
    post:
      tags:
        - users
      summary: Авторизация пользователя
      description: Авторизует пользователя на основе логина и пароля

    get:
      tags:
        - users
      summary: Проверка состояния пользователя
      description: Возвращает информацию по авторизованному пользователю

  /users/logout:
    delete:
      tags:
        - users
      summary: Деавторизация пользователя
      description: Деавторизует пользователя на основе логина и пароля

  /users/{userId}/avatar:
    post:
      tags:
        - users
      summary: Загрузить изображение аватара
      description: Загружает изображение аватара пользователя. Изображение
        аватара должно быть в формате `png` или `jpg`.

  /offers:
    get:
      tags:
        - offers
      summary: Список предложений по аренде
      description: Возвращает список предложений по аренде.

    post:
      tags:
        - offers
      summary: Создание нового предложения по аренде
      description: Создаёт новое предложение по аренде.

  /offers/{offerId}:
    get:
      tags:
        - offers
      summary: Детальная информация по предложению по аренде
      description: Возвращает детальную информацию по предложению по аренде.

    put:
      tags:
        - offers
      summary: Редактирование предложения по аренде
      description: Редактирует предложение по аренде.

    delete:
      tags:
        - offers
      summary: Удаление предложения по аренде
      description: Удаляет предложение по аренде.

  /premium:
    get:
      tags:
        - offers
      summary: Премиальные предложения для города
      description: Возвращает список премиальных предложений по аренде.

  /favorites:
    get:
      tags:
        - offers
      summary: Список избранных предложений
      description: Возвращает список избранных предложений по аренде.

  /favorites/{offerId}/{status}:
    post:
      tags:
        - offers
      summary: Добавление и удаление предложения в/из избранного
      description: Добавляет и удаляет предложение в/из избранного.

  /comments/{offerId}:
    get:
      tags:
        - offers
      summary: Список комментариев для предложения по аренде
      description: Возвращает список комментариев для предложения по аренде.

    post:
      tags:
        - comments
      summary: Создание нового комментария к предложению по аренде
      description: Создаёт новый комментарий к предложению по аренде.
